export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/device'
export const ABOUT_ROUTE = '/about'
export const ORGANIZATION_ROUTE = '/organization'
export const CONTACTS_ROUTE = '/contacts'
export const SUBCATEGORY_ROUTE = '/catalog'
export const FAVORITE_ROUTE = '/favorite'

